name: MediaWiki fetch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 0'

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Run script
        env:
          MW_USERNAME: ${{ secrets.MW_USERNAME }}
          MW_PASSWORD: ${{ secrets.MW_PASSWORD }}
          MW_ENDPOINT: ${{ secrets.MW_ENDPOINT }}
          MW_API: ${{ secrets.MW_API }}
          MW_SOURCE_PAGE: "Template:編集テスト/preload"
          MW_DIST_PAGE: "Minecraft Japan Wiki:編集テスト"
        run: node actions/post.mjs